version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=-1 fmriprep_stats.ipynb --output fmriprep_stats.ipynb
            git config credential.helper 'cache --timeout=120'
            git config user.email "stast@bot.com"
            git config user.name "stats-bot"
            git add fmriprep_stats.ipynb
            git commit -m "updating stats"
            git push https://${GITHUB_TOKEN}@github.com/poldracklab/fmriprep_stats.git master
          no_output_timeout: 60m 

      - store_artifacts:
          path: test-reports
          destination: test-reports